name=ADC128D818
version=0.2.0
author=Jose Luu <jose.luu@gmail.com>
maintainer=Jose Luu <jose.luu@gmail.com>
sentence=Arduino library for controlling ADC128D818 an I2C 8 channel ADC.
paragraph=Library for controlling ADC128D818 exposing a class help polling a gathering values.
category=Sensors
url=https://github.com/joseluu/adc128d818_driver
architectures=*
includes=ADC128D818.h